DROP TABLE IF EXISTS satellite;
DROP TABLE IF EXISTS planet;

CREATE TABLE planet
(
    ID SERIAL PRIMARY KEY ,
    NAME VARCHAR(255)  ,
    SURFACE_AREA BIGINT ,
    MASS BIGINT  ,
    DISTANCE_FROM_SUN BIGINT  ,
    AVERAGE_SURFACE_TEMPERATURE INTEGER,
    DELETED BOOLEAN
);

CREATE TABLE satellite
(
    ID SERIAL PRIMARY KEY ,
    NAME VARCHAR(255) NOT NULL ,
    SURFACE_AREA BIGINT NOT NULL ,
    MASS BIGINT NOT NULL ,
    NATURAL_SATELLITE BOOLEAN ,
    PLANET_ID BIGINT,
    FOREIGN KEY (PLANET_ID)
    REFERENCES PLANET(ID)
);